{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "analytics-worker.fullname" . }}
  labels:
    {{- include "analytics-worker.labels" . | nindent 4 }}
{{- end }}
